### ISSUE TITLE
Error: 'off_t' does not name a type.

### ISSUE THREAD

**Issue by mrwert** [guidoreina/gweb-plusplus#1]
Hello :)
[error]
xml/xml_document.h:71:16 error: 'off_t' does not name a type.
FreeBSD, OpenBSD.
[solution]
`#include <sys/types.h>` -> xml/xml_document.h
Thanks! :)

**Comment by guidoreina** [comment]
Thank you very much :)
I have just committed.
I remember I added some `#include <sys/types.h>` for `off_t` because it didn't compile under FreeBSD/OpenBSD/NetBSD. It seems I added more features and didn't try to compile anymore under them.

**Comment by mrwert** [comment]
Thanks! :)

**Comment by guidoreina** [comment]
Thanks to you for checking my projects and helping me to make them better :)
This is my oldest webserver. It has FastCGI and reverse proxy, but it doesn't support HTTPS or multiple listeners. gwebs++ supports HTTPS and multiple listeners but doesn't support FastCGI or reverse proxy.

**Comment by mrwert** [comment]
I tested reverse proxy.
I want to see reverse proxy in the gwebs++ :)

**Comment by guidoreina** [comment]
I would also love to see reverse proxy in gwebs++ ;).
I left the gwebs++ unfinished and did something else. Sometimes I come back to an old project and keep working on it.
What I would like to do first is to update the gwebs++ with the classes from the downloader project (which is my last network-related project). First I wrote the gweb++, then the gwebs++ and then the downloader, always trying to improve the networking core :)

**Comment by mrwert** [comment]
I will be testing the gwebs++ project on the FreeBSD, OpenBSD, DragonFly BSD, Debian, and maybe on the Minix :)

**Comment by guidoreina** [comment]
FreeBSD, OpenBSD and DragonFly are very similar so, when I ported it to FreeBSD I got the other ones almost for free :). Minix is different, it doesn't support so many things are the others do. My latest classes in the networking code are in the project downloader.
What I would like to do is to do another iteration and add thread support to the networking code :)

**Comment by mrwert** [comment]
It's Awesome! :)

I'm interested in the performance and resource consumption on the various BSD systems for the compiled (with Clang and GCC) gweb++ project. 
I learn c/c++ on real projects :)
Sorry for my bad English :)

**Comment by guidoreina** [comment]
I don't know what is the performance difference between the BSD variants, and/or Linux, it would be interesting to know. Many years ago I had another webserver and did some performance tests, but don't remember :).
You can write me an email, if you want, you can find my email here:
https://github.com/guidoreina/gSMTP/blob/master/SmtpServer.conf
That's another oooold project.
Your English is very good, I bet better than mine :)

**Comment by mrwert** [comment]
When I get objective information, I will write to your email.
Thanks :)
